name: .NET MAUI Build

on:
  push:
    branches: [ "main", "release", "develop" ]
  pull_request:
    branches: [ "main", "release", "develop" ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Debug, Release]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore OOSDD_GroceryApp_Sprint2_Studenten/Grocery.sln

      - name: Build solution
        run: dotnet build OOSDD_GroceryApp_Sprint2_Studenten/Grocery.sln --configuration ${{ matrix.configuration }} --no-restore

      - name: Run tests
        run: dotnet test --no-build --verbosity normal

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: GroceryApp-${{ matrix.configuration }}
          path: |
            **/bin/${{ matrix.configuration }}/net*/publish/
            **/bin/${{ matrix.configuration }}/net*/Grocery.*
